config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url #ログインしていなかったらログインページへ強制的にリダイレクト。
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in #application_controllerで定義されている。action前にログインを確認する
  before_action :correct_user, only: [:show, :edit, :destroy, :update]
  
  def index
    @task = current_user.tasks.build
    @tasks = current_user.tasks.order(id: :desc)
    @user = User.find(session[:user_id])
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(tasks_params)
    if @task.save
      flash[:success] = 'Taskを投稿しました。'
      redirect_to root_url
    else
      @tasks = current_user.tasks.order(id: :desc)
      flash.now[:danger] = 'Taskの投稿に失敗しました。'
      render :new
    end
  end

  def update
    if @task.update(tasks_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_to tasks_url
    # redirect_back(fallback_location: root_path)
  end
  
  def edit
  end
  
  
  
  private
  
  def tasks_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end

  #同じコードを共通化。GET,POSTやURLのパラメータやデータは全てparamsに代入されて受け取れます
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    # @users = User.order(id: :desc)
  end
  
  def show
    # @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>

<div>
    <%= task %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

<% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= f.label :status, 'ステータス' %>

<%= f.text_field :status %>
  
<%= f.label :content, 'メッセージ' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>
  <%= form_with(model: @task, local: true) do |f| %>
    <div class="form-group">
      <%= f.label 'ステータス' %>
      <%= f.text_field :status %>
    </div>
    <div>
      <%= f.label 'タスク' %>
      <%= f.text_area :content %>
    </div>
    <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
  <% end %>
        
<%= link_to '一覧へ戻る', root_path %>

app/views/tasks/index.html.erb
<h1><%= @user.name %>のタスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> : <%= task.status %> &gt; <%= task.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの投稿', new_task_path %>
<%= link_to 'ログアウト', logout_path, method: :delete %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', root_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>


<p>ステータス: <%= @task.status %></p>
<p>タスク: <%= @task.content %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このメッセージを編集する', edit_task_path(@task) %>
<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？'} %>
<!-- link_to 表示文字列, リンク先 -->
<!-- 「method: :delete」はDELETEメソッドを送信することを明示している -->

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @task, local: true) do |f| %>
        <div class="form-group">
          <%= f.label 'ステータス' %>
          <%= f.text_field :status %>
        </div>
        <div>
          <%= f.label 'タスク' %>
          <%= f.text_area :content %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
        
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'tasks/tasks', tasks: @tasks %>
      
    </div>
    <%= link_to 'Logout', logout_path, method: :delete %>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Tasklist</h1>
      <ul>
        <li><%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %></li>
        <li><%= link_to 'Login', login_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div>
  <div>

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit 'Sign up' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
    </div>
  </aside>
</div>